### PR TITLE
Refactor/localization

### LINKED ISSUE #109: Refactor localization
## Feature description 

Currently we out localization is too fake.
## Implementation proposal

Implement a more realistic localization using json files

### PR DESCRIPTION
**Pull request by ryuash**
## Description

closes #109 
CHANGES:
- localization is now in `en.json`
- `PostsLocalizations.of(context).translate(Message.accountScreenTitle)` example of how localization will now work
- will return an empty string if key is not found in json
## Checklist
- [x] Targeted PR against correct branch.
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Wrote unit tests.
- [x] Run flutter format.
- [ ] Updated the documentation.
- [ ] Added an entry to the `CHANGELOG.md` file.
- [x] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by ryuash** [comment]
@RiccardoM I actually worked off your UI test branch (whoops but should be fine. I just wanted to merge in the localization first before tackling the ui tests). Anyways wanted you to take a quick look, will we ever use localization outside of UI? Ex. in one of the `try/catch` source implementations we hit an error and want to send a message back to the UI.

**Comment by rmontagnin** [comment]
> will we ever use localization outside of UI? Ex. in one of the `try/catch` source implementations we hit an error and want to send a message back to the UI.

Ideally, not. What should happen instead is we are going to throw different exceptions (represented by different classes) and then translate them into messages for the user when they are caught inside the Bloc. Also because we cannot know from the repository or source how the Bloc is going to display such errors (a popup, an error message associated to an input field, etc).

**Comment by rmontagnin** [comment]
@ryuash I'm not a big fan of using variable strings inside the `.translate("")` method. If one translation is used in multiple places, this can lead to typos all over the place if the developer is not careful enough. In order to take advantage of the compile errors, can we create a class full of `static const` variables that represent the different JSON keys and use them instead? 

So this 

```dart
 PostsLocalizations.of(context).translate("appName")
```

Can become this

```dart
class Messages { 
  static const APP_NAME = "appName"; 
  // ...
}

PostsLocalizations.of(context).translate(Messages.APP_NAME);
```

This would make sure that developers cannot do typos when specifying the message that should be used.

**Comment by ryuash** [comment]
@RiccardoM can merge this first if you will be touching ui anytime soon. I'm on a different branch for the actual ui testings

**Review by rmontagnin — APPROVED** [review]

**Pull request merged**
