### PR TITLE
Fix/misleading poll 86

### LINKED ISSUE #86: Misleading poll creation UI
## Generic information
- OS name and version: iOS/Android
- Application build code: `4102`
- Network type (mobile/Wi-Fi): Both

If I’m writing a poll and I don’t pay much attention reading the _‘What do you want to ask?’_ section, I won’t see any differences between that and the various answers of the poll. I think more than one person could get it wrong (as in the example)

## Steps to reproduce
1. Enter the post creation screen
2. Add a poll to the post

## Expected behavior
The UI should reflect better the meaning of each input field.

### PR DESCRIPTION
**Pull request by ryuash**
## Description

fixes #86 
Removed poll question, instead we will use the status and fixed up some styling to match wireframe
Screen Shot 2020-07-24 at 11 16 03 AM
<hr>
Screen Shot 2020-07-24 at 11 16 03 AM

## Checklist
- [x] Targeted PR against correct branch.
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit tests.
- [x] Run flutter format.
- [ ] Updated the documentation.
- [x] Added an entry to the `CHANGELOG.md` file.
- [x] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by ryuash** [comment]
@RiccardoM so i only updated the visuals for the poll. Should i also remove the `poll.question` key from the entities and whats being sent to the chain? Would it break any backend code?

**Comment by rmontagnin** [comment]
@ryuash I would advise against removing the `question` key from the `PollData` to be honest. The backend is based on Desmos, which requires that key when sending a poll as you can see from the [documentation](https://docs.desmos.network/types/posts/post-poll-data.html).

**Review by rmontagnin — APPROVED** [review]
@ryuash I know the wireframe does not include it, but do you think we can add a way to tell the user which option he voted when viewing the poll results? 

Something similar to what Twitter does maybe: 

Buy-Win-Twitter-Poll

**Comment by ryuash** [comment]
@RiccardoM
Screen Shot 2020-07-27 at 9 48 55 AM
Screen Shot 2020-07-27 at 9 49 06 AM

**Pull request merged**
